name = "coupang-best-proxy"
main = "worker.js"
compatibility_date = "2025-09-01"

# wrangler kv namespace create CACHE 로 받은 id를 넣으세요
[[kv_namespaces]]
binding = "CACHE"
id = "9b8370d20a9646b9aa73f63c9200379f"

[vars]
# 블로그 주소(쉼표로 여러 개 가능). 비워 두면 모든 곳에서 호출 가능
ALLOWED_ORIGINS = "http://coupas.lsy38.com/"
